version: "3.8"


services:

    nginx:
        container_name: nginx
        image: nginx:1.25.3-bookworm
        ports:
            - "8000:80"
        volumes:
            - ./sites:/var/www
            - ./config/nginx:/etc/nginx/conf.d
            - ./data/logs:/var/log/nginx/
        depends_on:
            - php
            - mysql
        networks:
            - devnet

    php:
        container_name: php
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./sites:/var/www
            - ./config/php/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "9000:9000"
        networks:
            - devnet

    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        command: --innodb_use_native_aio=0
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - devnet

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - "8001:80"
        environment:
            PMA_HOST: mysql
        networks:
            - devnet


networks:
    devnet:
        driver: bridge
